### ISSUE TITLE
Using the docker example leads to a crash

### ISSUE THREAD

**Issue by yduf** [DigitalState/camunda-rest-jwt-authentication#7]
Hello,

very interested by this, try the docker example.
I had to comment the copy of docker/camunda/conf/bpm-platform.xml otherwise service doesn't start.

Yet I have not successfully run it => service start ok
but when I try to access the rest API (for ex: /engine-rest/engine)
- it gives me a 404 when no bearer token is povided (from camunda doc I was expected this to not be secure)
- it gives me the same 404 when provided the token as described in your readme, like if the rest
service is not working. But camunda cokpit ui is fine, telling me the engine is green.
And there is no obvious log on docker console.

Any idea what I am doing wrong ?

Regards,

Yves

PS : I also had to change the dependancy (groupid/artifactid) in order to build the example there were looking wrong.

**Comment by StephenOTT** [comment]
@yduf  what is your specific error?

When you download the Repo, and go to /examples/docker/tomcat/ and run `docker-compose up`

What is the specific error.  It works without issue when testing that exact process.

**Comment by yduf** [comment]
When I do;
$  git clone https://github.com/DigitalState/camunda-rest-jwt-authentication.git
$ cd  camunda-rest-jwt-authentication/examples/docker/tomcat/
$ docker-compose up
(assuming that what you expected me to do)

I got the log attached below.
[camunda.log](https://github.com/DigitalState/camunda-rest-jwt-authentication/files/2680980/camunda.log)

(doing that it's not clear for me how the jar is being build).

**Comment by StephenOTT** [comment]
I have update added the default example jars into: https://github.com/DigitalState/camunda-rest-jwt-authentication/commit/523737d85519a3aab5e7dfddb22b63b51411c2e5

This should make it easier to test for you.

**Comment by StephenOTT** [comment]
@yduf test with the example folder again with the latest commit, and see if you are getting the same issue.  Do a fresh download of the repo and do not change anything in the examples folder.

make sure to use `docker-compose up --build` to ensure new images are built.

**Comment by yduf** [comment]
Thanks for providing the jar. I was missing the docker-compose up --build, 
that's why, I was encountering the  bpm-platform.xml issue.

In the end, I still had a problem: all the issue were link to permissions issue, that's why the camunda engine failed to start while trying to load the jwt authentication plugin.

doing a `chmod a+rwX -R`  on docker folderand relaunching with `docker-compose up --build`  solved it.

=> the plugin works now and I got a 401 when trying to access the API / and the right answer when positioning the token.

Thanks for the help!

**Comment by StephenOTT** [comment]
Glad you got it worked out!
